#![allow(clippy::unwrap_used, clippy::expect_used)]

//! One real request over a real TLS connection.
//!
//! Everything else in `daemon::api` is tested at a seam: the parser over an
//! in-memory stream, the router over a constructed `Request`. This is the piece
//! that only a socket can check, so it wires the actual pieces together: a
//! certificate chain in lego's layout, `serve_connection` on one end, a rustls
//! client that verifies against the issuing CA on the other.
//!
//! The certificate is generated by `openssl` into a tempdir at test time rather
//! than committed, so this repository ships no private key. Without `openssl` on
//! `PATH` the test reports what it skipped instead of passing quietly.

#![cfg(unix)]

use super::*;

use std::io::{Read, Write};
use std::path::Path;

use crate::daemon::api::routes::ApiContext;
use crate::daemon::api::token::AuthToken;
use crate::profile::{AppConfig, AppState};
use crate::testutil::{HomeSandbox, SERVER_NAME, generate_chain};

const TOKEN: &str = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

/// A client that trusts only the CA just generated, so a handshake succeeding
/// means the server really presented a chain back to it.
fn client_config(ca_crt: &Path) -> Option<std::sync::Arc<rustls::ClientConfig>> {
    use rustls::pki_types::CertificateDer;
    use rustls::pki_types::pem::PemObject;

    let mut roots = rustls::RootCertStore::empty();
    for cert in CertificateDer::pem_file_iter(ca_crt).ok()? {
        roots.add(cert.ok()?).ok()?;
    }
    let provider = std::sync::Arc::new(rustls::crypto::ring::default_provider());
    Some(std::sync::Arc::new(
        rustls::ClientConfig::builder_with_provider(provider)
            .with_safe_default_protocol_versions()
            .ok()?
            .with_root_certificates(roots)
            .with_no_client_auth(),
    ))
}

fn ctx() -> std::sync::Arc<ApiContext> {
    let config = std::sync::Arc::new(crate::lockorder::RankedMutex::new(AppConfig {
        state: AppState::default(),
        profiles: Vec::new(),
    }));
    let status_path = crate::profile::clauth_dir().unwrap().join("status.json");
    ApiContext::new(config, status_path, AuthToken::from_plaintext(TOKEN), None)
}

/// A TLS client connection that can be driven request by request.
///
/// Responses are framed by their `Content-Length` rather than by reading to end
/// of stream, which is the whole point: on a persistent connection there is no
/// close to read to, and finding where one response stops is exactly what a
/// client has to do to reuse the connection.
struct Session {
    stream: rustls::StreamOwned<rustls::ClientConnection, std::net::TcpStream>,
    buf: Vec<u8>,
}

impl Session {
    fn connect(port: u16, client: &std::sync::Arc<rustls::ClientConfig>) -> std::io::Result<Self> {
        let name = rustls::pki_types::ServerName::try_from(SERVER_NAME)
            .map_err(std::io::Error::other)?
            .to_owned();
        let conn = rustls::ClientConnection::new(std::sync::Arc::clone(client), name)
            .map_err(std::io::Error::other)?;
        let sock = std::net::TcpStream::connect(("127.0.0.1", port))?;
        sock.set_read_timeout(Some(std::time::Duration::from_secs(10)))?;
        Ok(Self {
            stream: rustls::StreamOwned::new(conn, sock),
            buf: Vec::new(),
        })
    }

    fn send(&mut self, request: &str) -> std::io::Result<()> {
        self.stream.write_all(request.as_bytes())?;
        self.stream.flush()
    }

    /// One response: its head, and its body of exactly `Content-Length` bytes.
    /// Anything already read past it stays buffered for the next call.
    fn recv(&mut self) -> std::io::Result<(String, String)> {
        let mut chunk = [0u8; 512];
        let head_end = loop {
            if let Some(i) = self.buf.windows(4).position(|w| w == b"\r\n\r\n") {
                break i + 4;
            }
            let n = self.stream.read(&mut chunk)?;
            if n == 0 {
                return Err(std::io::Error::other("eof before a response head"));
            }
            self.buf.extend_from_slice(&chunk[..n]);
        };
        let head = String::from_utf8_lossy(&self.buf[..head_end]).into_owned();
        let len: usize = head
            .lines()
            .find_map(|line| {
                let (name, value) = line.split_once(':')?;
                name.eq_ignore_ascii_case("content-length")
                    .then(|| value.trim().parse().ok())?
            })
            .ok_or_else(|| std::io::Error::other("response has no Content-Length"))?;
        while self.buf.len() < head_end + len {
            let n = self.stream.read(&mut chunk)?;
            if n == 0 {
                return Err(std::io::Error::other("eof before a response body"));
            }
            self.buf.extend_from_slice(&chunk[..n]);
        }
        let body = String::from_utf8_lossy(&self.buf[head_end..head_end + len]).into_owned();
        self.buf.drain(..head_end + len);
        Ok((head, body))
    }
}

/// One request on its own connection, for the cases that end in a close.
fn round_trip(
    port: u16,
    client: &std::sync::Arc<rustls::ClientConfig>,
    request: &str,
) -> std::io::Result<String> {
    let mut session = Session::connect(port, client)?;
    session.send(request)?;
    let (head, body) = session.recv()?;
    Ok(format!("{head}{body}"))
}

#[test]
fn a_real_tls_request_is_served_end_to_end() {
    let dir = tempfile::tempdir().expect("tempdir");
    let Some((paths, ca_crt)) = generate_chain(dir.path()) else {
        eprintln!("SKIPPED a_real_tls_request_is_served_end_to_end: openssl is not usable here");
        return;
    };
    let server_tls = tls::server_config_from(&paths).expect("server config");
    let Some(client_tls) = client_config(&ca_crt) else {
        eprintln!("SKIPPED a_real_tls_request_is_served_end_to_end: client config");
        return;
    };

    let home = HomeSandbox::new();
    let ctx = ctx();
    let feed = r#"{"schema":1,"active_profile":"alpha","profiles":[]}"#;
    crate::profile::mkdir_700(&crate::profile::clauth_dir().unwrap()).expect("mkdir");
    std::fs::write(&ctx.status_path, feed).expect("seed feed");

    let listener = std::net::TcpListener::bind(("127.0.0.1", 0)).expect("bind");
    let port = listener.local_addr().expect("addr").port();

    // Three connections, served one at a time on a worker thread: the
    // authenticated read, an unauthenticated one, and a request for a path that
    // does not exist.
    std::thread::scope(|scope| {
        scope.spawn(|| {
            for _ in 0..3 {
                let (stream, peer) = listener.accept().expect("accept");
                serve_connection(stream, peer, &server_tls, &ctx, Limits::DEFAULT);
            }
        });

        let authorized = round_trip(
            port,
            &client_tls,
            &format!(
                "GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\nConnection: close\r\n\r\n"
            ),
        )
        .expect("authorized round trip");
        assert!(
            authorized.starts_with("HTTP/1.1 200 OK\r\n"),
            "{authorized}"
        );
        assert!(
            authorized.ends_with(feed),
            "the published feed must arrive intact over TLS: {authorized}"
        );

        let anonymous = round_trip(
            port,
            &client_tls,
            &format!(
                "GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\nConnection: close\r\n\r\n"
            ),
        )
        .expect("anonymous round trip");
        assert!(
            anonymous.starts_with("HTTP/1.1 401 Unauthorized\r\n"),
            "{anonymous}"
        );
        assert!(
            !anonymous.contains("active_profile"),
            "an unauthenticated caller must learn no account names: {anonymous}"
        );

        let missing = round_trip(
            port,
            &client_tls,
            &format!(
                "GET /api/v1/nope HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\nConnection: close\r\n\r\n"
            ),
        )
        .expect("404 round trip");
        assert!(
            missing.starts_with("HTTP/1.1 404 Not Found\r\n"),
            "{missing}"
        );
    });

    drop(home);
}

/// A test fixture's whole world: a certificate, a seeded feed, and a listener.
/// Returns the port plus everything the caller has to keep alive.
struct Fixture {
    port: u16,
    listener: std::net::TcpListener,
    server_tls: std::sync::Arc<rustls::ServerConfig>,
    client_tls: std::sync::Arc<rustls::ClientConfig>,
    ctx: std::sync::Arc<ApiContext>,
    feed: String,
    _home: HomeSandbox,
    _dir: tempfile::TempDir,
}

/// `None` when openssl cannot produce a certificate here.
fn fixture() -> Option<Fixture> {
    let dir = tempfile::tempdir().expect("tempdir");
    let (paths, ca_crt) = generate_chain(dir.path())?;
    let server_tls = tls::server_config_from(&paths).expect("server config");
    let client_tls = client_config(&ca_crt)?;

    let home = HomeSandbox::new();
    let ctx = ctx();
    let feed = r#"{"schema":1,"active_profile":"alpha","profiles":[]}"#.to_string();
    crate::profile::mkdir_700(&crate::profile::clauth_dir().unwrap()).expect("mkdir");
    std::fs::write(&ctx.status_path, &feed).expect("seed feed");

    let listener = std::net::TcpListener::bind(("127.0.0.1", 0)).expect("bind");
    let port = listener.local_addr().expect("addr").port();
    Some(Fixture {
        port,
        listener,
        server_tls,
        client_tls,
        ctx,
        feed,
        _home: home,
        _dir: dir,
    })
}

/// Relay `client -> upstream`, splitting each chunk in half with a pause
/// between the halves once `fragment` is set, so the server's read timeout
/// lands INSIDE a TLS record rather than on a record boundary. Returns the port
/// to point a client at.
///
/// Fragmentation is switched on rather than always-on because the handshake and
/// the first request share one budget (`io_timeout`); splitting those would
/// test the budget rather than the resumption this exists for.
///
/// Handles exactly one connection and stops when either side closes.
///
/// Runs on a detached thread holding only owned data. That is safe here where
/// it usually would not be: it never resolves a path or touches `~/.clauth`, so
/// it cannot outlive the test's `HomeSandbox` and reach the operator's real
/// tree. It ends when either side closes, or on its own read deadline.
fn fragmenting_proxy(
    upstream: u16,
    pause: std::time::Duration,
    fragment: std::sync::Arc<std::sync::atomic::AtomicBool>,
) -> u16 {
    let listener = std::net::TcpListener::bind(("127.0.0.1", 0)).expect("bind proxy");
    let port = listener.local_addr().expect("proxy addr").port();

    std::thread::spawn(move || {
        let (client, _) = listener.accept().expect("proxy accept");
        let server = std::net::TcpStream::connect(("127.0.0.1", upstream)).expect("proxy connect");
        let deadline = std::time::Duration::from_secs(20);
        client.set_read_timeout(Some(deadline)).ok();
        server.set_read_timeout(Some(deadline)).ok();

        let (mut c_read, mut c_write) = (
            client.try_clone().expect("clone client"),
            client.try_clone().expect("clone client"),
        );
        let (mut s_read, mut s_write) = (
            server.try_clone().expect("clone server"),
            server.try_clone().expect("clone server"),
        );

        std::thread::scope(|inner| {
            // Server to client: straight through.
            inner.spawn(move || {
                let mut buf = [0u8; 4096];
                while let Ok(n) = s_read.read(&mut buf) {
                    if n == 0 || c_write.write_all(&buf[..n]).is_err() {
                        break;
                    }
                }
                let _ = c_write.shutdown(std::net::Shutdown::Write);
            });
            // Client to server: once armed, each chunk arrives as two pieces
            // with a gap between them.
            let mut buf = [0u8; 4096];
            while let Ok(n) = c_read.read(&mut buf) {
                if n == 0 {
                    break;
                }
                let split = if fragment.load(std::sync::atomic::Ordering::Acquire) {
                    (n / 2).max(1)
                } else {
                    n
                };
                if s_write.write_all(&buf[..split]).is_err() {
                    break;
                }
                let _ = s_write.flush();
                if split < n {
                    std::thread::sleep(pause);
                    if s_write.write_all(&buf[split..n]).is_err() {
                        break;
                    }
                    let _ = s_write.flush();
                }
            }
            let _ = s_write.shutdown(std::net::Shutdown::Write);
        });
    });
    port
}

/// The subtle half of the fix: a read timeout can land part-way through a TLS
/// record, not just on a message boundary.
///
/// The retry has to resume from rustls's buffered partial record rather than
/// treating it as a failure. If it did not, a client whose packets fragment
/// (any real network) would fail even though it was sending normally.
///
/// Only the SECOND request is fragmented. The handshake and the first request
/// share one budget (`io_timeout`, the first-request deadline), so splitting
/// those across timeouts would exhaust that budget and test it rather than the
/// resumption this is about.
#[test]
fn a_read_timeout_inside_a_tls_record_resumes() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED a_read_timeout_inside_a_tls_record_resumes: openssl is not usable here");
        return;
    };
    // The pause between halves comfortably exceeds one io timeout, so the
    // record the server reads spans at least one timeout.
    let limits = Limits {
        io_timeout: std::time::Duration::from_millis(80),
        lifetime: std::time::Duration::from_secs(30),
        max_requests: 100,
    };
    let fragment = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, limits);
        });
        let proxy_port = fragmenting_proxy(
            f.port,
            std::time::Duration::from_millis(250),
            std::sync::Arc::clone(&fragment),
        );

        let get = format!(
            "GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
             Authorization: Bearer {TOKEN}\r\n\r\n"
        );
        let mut session = Session::connect(proxy_port, &f.client_tls).expect("connect via proxy");

        // Handshake and first request unfragmented, so the connection is
        // established and on the generous idle budget.
        session.send(&get).expect("first send");
        let (head, _) = session.recv().expect("first recv");
        assert!(head.contains("Connection: keep-alive\r\n"), "{head}");

        // Now split every record across a read timeout.
        fragment.store(true, std::sync::atomic::Ordering::Release);
        session
            .send(&get)
            .expect("send through the fragmenting proxy");
        let (head, body) = session
            .recv()
            .expect("a record split across a read timeout must resume, not fail");
        assert!(head.starts_with("HTTP/1.1 200 OK\r\n"), "{head}");
        assert_eq!(body, f.feed);
    });
}

/// Three requests down ONE connection, each sent only after the previous
/// response was read. The TLS handshake happens once.
#[test]
fn a_connection_is_reused_across_requests() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED a_connection_is_reused_across_requests: openssl is not usable here");
        return;
    };

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, Limits::DEFAULT);
        });

        let mut session = Session::connect(f.port, &f.client_tls).expect("connect");
        for i in 0..3 {
            session
                .send(&format!(
                    "GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                     Authorization: Bearer {TOKEN}\r\n\r\n"
                ))
                .unwrap_or_else(|e| panic!("send {i}: {e}"));
            let (head, body) = session.recv().unwrap_or_else(|e| panic!("recv {i}: {e}"));
            assert!(
                head.starts_with("HTTP/1.1 200 OK\r\n"),
                "request {i}: {head}"
            );
            assert!(
                head.contains("Connection: keep-alive\r\n"),
                "request {i} should have been told the connection survives: {head}"
            );
            assert!(head.contains("Keep-Alive: timeout="), "request {i}: {head}");
            assert_eq!(body, f.feed, "request {i}");
        }

        // Asking to close ends it, and the server says so on the way out.
        session
            .send(&format!(
                "GET /api/v1/health HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\nConnection: close\r\n\r\n"
            ))
            .expect("send close");
        let (head, _) = session.recv().expect("recv close");
        assert!(head.starts_with("HTTP/1.1 200 OK\r\n"), "{head}");
        assert!(head.contains("Connection: close\r\n"), "{head}");
    });
}

/// Two requests written in ONE call, before either response is read, and the
/// responses must come back in the order they were asked for.
#[test]
fn pipelined_requests_are_answered_in_order() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED pipelined_requests_are_answered_in_order: openssl is not usable here");
        return;
    };

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, Limits::DEFAULT);
        });

        let mut session = Session::connect(f.port, &f.client_tls).expect("connect");
        // The distinguishing move: both requests hit the wire together, so the
        // server reads the second out of the buffer left by the first.
        session
            .send(&format!(
                "GET /api/v1/health HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\n\r\n\
                 GET /api/v1/nope HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\n\r\n\
                 GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\nConnection: close\r\n\r\n"
            ))
            .expect("send pipeline");

        let (first, first_body) = session.recv().expect("first response");
        assert!(first.starts_with("HTTP/1.1 200 OK\r\n"), "{first}");
        assert!(
            first_body.contains("\"schema\""),
            "the first response must be health's, not another route's: {first_body}"
        );

        let (second, _) = session.recv().expect("second response");
        assert!(
            second.starts_with("HTTP/1.1 404 Not Found\r\n"),
            "responses must not be reordered: {second}"
        );

        let (third, third_body) = session.recv().expect("third response");
        assert!(third.starts_with("HTTP/1.1 200 OK\r\n"), "{third}");
        assert_eq!(third_body, f.feed);
        assert!(
            third.contains("Connection: close\r\n"),
            "the last of the pipeline asked to close: {third}"
        );
    });
}

/// Short limits, so a whole connection lifecycle runs in milliseconds. The
/// ratios are what matter and they match production: an idle gap several times
/// the io timeout, well inside the lifetime.
fn brisk_limits() -> Limits {
    Limits {
        io_timeout: std::time::Duration::from_millis(150),
        lifetime: std::time::Duration::from_secs(30),
        max_requests: 100,
    }
}

/// The regression, end to end over TLS.
///
/// A client polling slower than the socket read timeout must still find its
/// connection alive. This is what was broken: the idle wait hit the 10s socket
/// timeout, the loop treated it as a failure, and every client polling slower
/// than 10s re-handshaked on every request while being told it had 120 seconds.
#[test]
fn a_connection_survives_an_idle_gap_longer_than_the_io_timeout() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED a_connection_survives_an_idle_gap: openssl is not usable here");
        return;
    };
    let limits = brisk_limits();

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, limits);
        });

        let mut session = Session::connect(f.port, &f.client_tls).expect("connect");
        let get = format!(
            "GET /api/v1/health HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
             Authorization: Bearer {TOKEN}\r\n\r\n"
        );

        session.send(&get).expect("first send");
        let (head, _) = session.recv().expect("first recv");
        assert!(head.contains("Connection: keep-alive\r\n"), "{head}");

        // Idle for several times the io timeout, the shape of a poll interval.
        std::thread::sleep(limits.io_timeout * 4);

        session
            .send(&get)
            .expect("the connection must survive an idle gap");
        let (head, _) = session
            .recv()
            .expect("a second request after idling must be answered on the same connection");
        assert!(head.starts_with("HTTP/1.1 200 OK\r\n"), "{head}");
        assert!(head.contains("Connection: keep-alive\r\n"), "{head}");
    });
}

/// The advertised budget is real in both directions: what a response promises
/// is what is left, and running out actually closes the connection.
#[test]
fn the_advertised_budget_is_the_one_enforced() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED the_advertised_budget_is_the_one_enforced: openssl is not usable here");
        return;
    };
    let limits = Limits {
        io_timeout: std::time::Duration::from_millis(100),
        lifetime: std::time::Duration::from_millis(700),
        max_requests: 100,
    };

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, limits);
        });

        let mut session = Session::connect(f.port, &f.client_tls).expect("connect");
        let get = format!(
            "GET /api/v1/health HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
             Authorization: Bearer {TOKEN}\r\n\r\n"
        );
        session.send(&get).expect("send");
        let (head, _) = session.recv().expect("recv");

        // What is advertised is what remains, so it can never exceed the budget
        // the connection was actually given.
        let advertised: u64 = head
            .lines()
            .find_map(|l| l.trim().strip_prefix("Keep-Alive: timeout="))
            .and_then(|rest| rest.split(',').next())
            .and_then(|n| n.trim().parse().ok())
            .unwrap_or_else(|| panic!("no Keep-Alive timeout in {head}"));
        assert!(
            advertised <= limits.lifetime.as_secs(),
            "advertised {advertised}s but the connection only has {}s: {head}",
            limits.lifetime.as_secs()
        );

        // Idle past the whole budget: the connection must be gone, not lingering.
        std::thread::sleep(limits.lifetime + std::time::Duration::from_millis(300));
        let _ = session.send(&get);
        assert!(
            session.recv().is_err(),
            "a connection past its advertised budget must be closed"
        );
    });
}

/// An unauthenticated caller gets no connection to hold. Persistent connections
/// would otherwise let anyone who can reach the port occupy a slot for the whole
/// budget with one bogus request and then silence.
#[test]
fn an_unauthenticated_request_does_not_keep_the_connection() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED an_unauthenticated_request_does_not_keep: openssl is not usable here");
        return;
    };

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, brisk_limits());
        });

        let mut session = Session::connect(f.port, &f.client_tls).expect("connect");
        session
            .send(&format!(
                "GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\r\n"
            ))
            .expect("send");
        let (head, _) = session.recv().expect("recv");
        assert!(head.starts_with("HTTP/1.1 401 Unauthorized\r\n"), "{head}");
        assert!(
            head.contains("Connection: close\r\n"),
            "a 401 must not leave a slot occupied: {head}"
        );
    });
}

/// A client that connects and never speaks gets the short first-request
/// deadline, not the full idle allowance. At 32 slots the difference is what a
/// trivial flood would exploit.
#[test]
fn a_silent_client_is_dropped_without_holding_a_slot_for_the_whole_lifetime() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED a_silent_client_is_dropped: openssl is not usable here");
        return;
    };
    let limits = brisk_limits();

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, limits);
        });

        // Raw TCP, no TLS: connect and say nothing at all.
        let mut sock = std::net::TcpStream::connect(("127.0.0.1", f.port)).expect("connect");
        sock.set_read_timeout(Some(limits.lifetime))
            .expect("timeout");
        let started = std::time::Instant::now();

        // Drain to end of stream. rustls emits a close_notify alert on the way
        // out even though no handshake completed, so the bytes seen here are
        // the shutdown itself; what this test is about is how long it took.
        let mut sink = [0u8; 64];
        loop {
            match sock.read(&mut sink) {
                Ok(0) | Err(_) => break,
                Ok(_) => continue,
            }
        }
        let waited = started.elapsed();

        assert!(
            waited < limits.lifetime / 2,
            "dropped after {waited:?}, which is the idle allowance rather than the \
             first-request deadline"
        );
    });
}

/// A framing error closes the connection rather than trying to find the next
/// message boundary on a stream someone else may be framing.
#[test]
fn a_framing_error_answers_and_closes_even_on_a_persistent_connection() {
    let Some(f) = fixture() else {
        eprintln!("SKIPPED a_framing_error_answers_and_closes: openssl is not usable here");
        return;
    };

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = f.listener.accept().expect("accept");
            serve_connection(stream, peer, &f.server_tls, &f.ctx, Limits::DEFAULT);
        });

        let mut session = Session::connect(f.port, &f.client_tls).expect("connect");
        // One good request to establish the connection, then chunked framing,
        // which this server refuses.
        session
            .send(&format!(
                "GET /api/v1/health HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\n\r\n"
            ))
            .expect("send good");
        let (head, _) = session.recv().expect("recv good");
        assert!(head.contains("Connection: keep-alive\r\n"), "{head}");

        session
            .send(&format!(
                "POST /api/v1/switch HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\
                 Authorization: Bearer {TOKEN}\r\n\
                 Transfer-Encoding: chunked\r\n\r\n0\r\n\r\n"
            ))
            .expect("send chunked");
        let (head, _) = session.recv().expect("recv refusal");
        assert!(head.starts_with("HTTP/1.1 400 Bad Request\r\n"), "{head}");
        assert!(
            head.contains("Connection: close\r\n"),
            "a framing error must not leave the connection open: {head}"
        );
    });
}

/// A plaintext client gets no response at all: there is no secure channel to
/// answer over, and the server must not fall back to one.
#[test]
fn a_plaintext_client_gets_nothing_back() {
    let dir = tempfile::tempdir().expect("tempdir");
    let Some((paths, _ca)) = generate_chain(dir.path()) else {
        eprintln!("SKIPPED a_plaintext_client_gets_nothing_back: openssl is not usable here");
        return;
    };
    let server_tls = tls::server_config_from(&paths).expect("server config");

    let _home = HomeSandbox::new();
    let ctx = ctx();
    let listener = std::net::TcpListener::bind(("127.0.0.1", 0)).expect("bind");
    let port = listener.local_addr().expect("addr").port();

    std::thread::scope(|scope| {
        scope.spawn(|| {
            let (stream, peer) = listener.accept().expect("accept");
            serve_connection(stream, peer, &server_tls, &ctx, Limits::DEFAULT);
        });

        let mut sock = std::net::TcpStream::connect(("127.0.0.1", port)).expect("connect");
        sock.set_read_timeout(Some(std::time::Duration::from_secs(10)))
            .expect("timeout");
        let _ = sock.write_all(
            format!("GET /api/v1/status HTTP/1.1\r\nHost: {SERVER_NAME}\r\n\r\n").as_bytes(),
        );

        let mut got = Vec::new();
        let _ = sock.read_to_end(&mut got);
        let text = String::from_utf8_lossy(&got);
        assert!(
            !text.contains("HTTP/1.1"),
            "a plaintext request must not draw a plaintext response: {text}"
        );
    });
}

/// The connection cap: the only thing between a flood and unbounded thread
/// creation. Serialized against the other tests in this file by
/// `LIVE_CONNECTIONS` being process-global, so it restores the counter itself.
#[test]
fn the_connection_cap_admits_up_to_the_limit_and_releases_on_drop() {
    // Nothing else in this binary claims a slot outside an accept loop, and no
    // accept loop runs in tests.
    assert_eq!(
        LIVE_CONNECTIONS.load(std::sync::atomic::Ordering::Acquire),
        0
    );

    SATURATION_LOGGED.store(false, std::sync::atomic::Ordering::Release);

    let mut slots: Vec<_> = (0..MAX_CONNECTIONS)
        .map(|i| claim_slot().unwrap_or_else(|| panic!("slot {i} should be admitted")))
        .collect();
    assert!(
        claim_slot().is_none(),
        "the {MAX_CONNECTIONS}th+1 connection must be refused, not queued"
    );

    // The "at capacity" line is once per episode, and this is what makes that
    // true: at the cap a flood ends one connection and takes its slot again
    // immediately, so re-arming on any release would put a line in the log per
    // refusal — the spam the flag exists to prevent, reached the long way round.
    //
    // Asserted here rather than in a test of its own because `LIVE_CONNECTIONS`
    // is process-global and these run as threads in one process: a second test
    // driving the same counter would race this one.
    assert!(
        SATURATION_LOGGED.load(std::sync::atomic::Ordering::Acquire),
        "the first refusal must arm the notice"
    );
    slots.pop();
    assert!(
        SATURATION_LOGGED.load(std::sync::atomic::Ordering::Acquire),
        "one connection finishing at the cap is not a new saturation episode"
    );
    slots.truncate(SATURATION_REARM_BELOW - 1);
    assert!(
        !SATURATION_LOGGED.load(std::sync::atomic::Ordering::Acquire),
        "coming back below {SATURATION_REARM_BELOW} live connections re-arms it"
    );

    drop(slots);
    assert_eq!(
        LIVE_CONNECTIONS.load(std::sync::atomic::Ordering::Acquire),
        0,
        "every slot must come back, or the cap shrinks for the process lifetime"
    );
    let reopened = claim_slot();
    assert!(
        reopened.is_some(),
        "capacity must be reusable once connections finish"
    );
    drop(reopened);
}

/// The listener's failures have to be reachable BEFORE the singleton claim.
///
/// `--replace` terminates the running daemon as part of claiming, so a
/// certificate that fails to load after that point takes the incumbent down and
/// then aborts, leaving the host with no daemon at all — no refresh, no
/// auto-switch, not merely no listener. `wiki/Daemon.md` recommends
/// `clauth daemon --replace --listen` as the post-`lego renew` hook, so the
/// documented automation is the trigger.
///
/// What this pins is that a bad certificate is discovered in `prepare`, which
/// needs no daemon lock, no config and no scheduler — so `daemon::serve` can
/// call it above the claim, and does.
///
/// The cert directory is pointed at an empty tempdir through `tls.json` rather
/// than relying on this host having no lego tree: the box this was written on
/// serves a real certificate out of `/etc/lego`, which `HomeSandbox` does not
/// redirect, so the obvious version of this test passed vacuously.
#[test]
fn a_missing_certificate_fails_in_prepare_not_after_the_claim() {
    let _home = HomeSandbox::new();
    let empty = tempfile::tempdir().expect("tempdir");
    let tls_json = crate::profile::clauth_dir().expect("dir").join("tls.json");
    #[allow(clippy::expect_used)]
    std::fs::create_dir_all(tls_json.parent().expect("has parent")).expect("mkdir");
    std::fs::write(
        &tls_json,
        serde_json::json!({ "schema": 1, "cert_dir": empty.path() }).to_string(),
    )
    .expect("write tls.json");

    // Matched rather than `expect_err`: that needs `Debug` on the success type,
    // and `Prepared` holds a bound socket and a rustls config — not a thing to
    // give a derived formatter to for a test's convenience.
    let Err(err) = super::prepare(
        "127.0.0.1:0".parse().expect("addr"),
        &crate::daemon::api::tls::CertSource::Lego,
    ) else {
        panic!("an empty certificate directory must fail in prepare");
    };
    let msg = format!("{err:#}");
    assert!(
        msg.contains(&empty.path().display().to_string()) || msg.contains(".crt"),
        "the failure names the path the operator has to fix: {msg}"
    );
}
